name: 'ca_dbt'
version: '1.0.0'

profile: 'ca_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ca_dbt:
    staging:
      +materialized: view
      +tags: ["staging"]

    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]

    marts:
      +materialized: table
      +tags: ["marts"]

seeds:
  ca_dbt:
    +tags: ["seed"]

snapshots:
  ca_dbt:
    +tags: ["snapshots"]